spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth?useOldAliasMetadataBehavior=true&serverTimezone=GMT%2b8
    username: root
    password: 123456

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: